[modengine]
debug = false
external_dlls = [
    "SeamlessCoop/ds3sc.dll",
    "proper_pc_experience_mod/d3d11.dll"
]

[extension.mod_loader]
enabled = true
loose_params = false
mods = [
    { enabled = true, name = "default", path = "mod" }
]

[extension.scylla_hide]
enabled = true